version: "3.9"
    
services:
  mysql:
    image: mysql_fh:v3
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DB: wordpress
      MYSQL_USER: admin
      MYSQL_PASS: admin1234
    
  wordpress:
    depends_on:
      - mysql
    image: wordpress_fh:v1
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASS: admin1234
volumes:
  mysql_data: {}
  wordpress_data: {}